/**
 * Helper Functions Module
 * Common utility functions for the application
 */

/**
 * Toggle help box visibility
 */
function toggleHelp(helpId) {
    const helpBox = document.getElementById(helpId);
    if (helpBox) {
        helpBox.classList.toggle('show');
    }
}

/**
 * Show username in header
 */
function displayUserName() {
    const username = sessionStorage.getItem('username');
    const userNameSpan = document.getElementById('userName');
    if (userNameSpan && username) {
        userNameSpan.textContent = username;
    }
}

/**
 * Copy text to clipboard
 */
function copyToClipboard(text) {
    if (navigator.clipboard) {
        navigator.clipboard.writeText(text).then(() => {
            showSuccessMessage('Copied to clipboard!');
        }).catch(err => {
            // Fallback method
            const textArea = document.createElement('textarea');
            textArea.value = text;
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand('copy');
            document.body.removeChild(textArea);
            showSuccessMessage('Copied to clipboard!');
        });
    }
}

/**
 * Show success message
 */
function showSuccessMessage(message) {
    // Create temporary success message
    const successDiv = document.createElement('div');
    successDiv.className = 'success-message show';
    successDiv.textContent = message;
    successDiv.style.position = 'fixed';
    successDiv.style.top = '20px';
    successDiv.style.right = '20px';
    successDiv.style.zIndex = '10000';
    document.body.appendChild(successDiv);
    
    setTimeout(() => {
        successDiv.remove();
    }, 3000);
}

/**
 * Download text as file
 */
function downloadAsFile(filename, text) {
    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
    element.setAttribute('download', filename);
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    showSuccessMessage('File downloaded!');
}

/**
 * Format results for export
 */
function formatResults(title, data) {
    let text = '='.repeat(50) + '\n';
    text += title + '\n';
    text += '='.repeat(50) + '\n\n';
    text += data;
    text += '\n\n';
    text += '='.repeat(50) + '\n';
    text += 'Generated by OS Simulator\n';
    text += 'Date: ' + new Date().toLocaleString() + '\n';
    text += '='.repeat(50) + '\n';
    return text;
}

/**
 * Show loading state
 */
function showLoading(elementId) {
    const element = document.getElementById(elementId);
    if (element) {
        element.innerHTML = '<div class="loading">Calculating</div>';
    }
}

/**
 * Initialize on page load
 */
document.addEventListener('DOMContentLoaded', function() {
    // Display username
    displayUserName();
    
    // Add keyboard shortcuts
    document.addEventListener('keydown', function(e) {
        // Ctrl/Cmd + H to toggle help
        if ((e.ctrlKey || e.metaKey) && e.key === 'h') {
            e.preventDefault();
            const activeSection = document.querySelector('.content-section.active');
            if (activeSection) {
                const helpBox = activeSection.querySelector('.help-box');
                if (helpBox) {
                    helpBox.classList.toggle('show');
                }
            }
        }
    });
});

// Make functions global
window.toggleHelp = toggleHelp;
window.copyToClipboard = copyToClipboard;
window.downloadAsFile = downloadAsFile;
window.formatResults = formatResults;
window.showSuccessMessage = showSuccessMessage;

